import jsPDF from "jspdf";
const generateReceipt = (payment) => {
  if (!payment) return;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Determine theme based on status
  const isSuccess = payment.status === "success";
  const themeColor = isSuccess ? [46, 204, 113] : [231, 76, 60]; // green / red
  const themeHex = isSuccess ? "#2ECC71" : "#E74C3C";

  // === HEADER SECTION ===
  doc.setFillColor(...themeColor);
  doc.rect(0, 0, pageWidth, 40, "F"); // header background

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("PAYMENT RECEIPT", pageWidth / 2, 25, { align: "center" });

  // === COMPANY INFO ===
  doc.setFontSize(10);
  doc.setTextColor(230);
  doc.text("Generated by AiShort Pvt. Ltd.", pageWidth / 2, 35, {
    align: "center",
  });

  // === BODY CONTENT ===
  doc.setTextColor(40);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);

  let y = 55;
  const lineGap = 10;

  // Payment Information Header
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...themeColor);
  doc.text("Payment Details", 20, y);
  y += lineGap;

  // === PAYMENT DETAILS BOX ===
  doc.setDrawColor(...themeColor);
  doc.setLineWidth(0.6);
  doc.roundedRect(15, y - 7, pageWidth - 30, 65, 3, 3);

  let infoY = y + 5;
  doc.setTextColor(60);
  doc.setFont("helvetica", "normal");
  doc.text(`Order ID: ${payment.orderId}`, 25, infoY);
  infoY += lineGap;
  doc.text(`Plan: ${payment.planName} (${payment.planType})`, 25, infoY);
  infoY += lineGap;
  doc.text(`Amount: ₹${payment.amount} ${payment.currency}`, 25, infoY);
  infoY += lineGap;
  doc.text(`Status: ${payment.status}`, 25, infoY);
  infoY += lineGap;
  doc.text(
    `Date: ${new Date(payment.createdAt).toLocaleString()}`,
    25,
    infoY
  );

  // === STATUS INDICATOR ===
  doc.setFillColor(...themeColor);
  doc.circle(pageWidth - 30, y + 25, 5, "F");

  // === FOOTER ===
  doc.setFont("helvetica", "italic");
  doc.setTextColor(100);
  doc.text("Thank you for your payment!", 20, 150);
  doc.setFontSize(10);
  doc.text("For support, contact: support@AiShort.com", 20, 160);

  // === SAVE PDF ===
  doc.save(`receipt_${payment.orderId || "payment"}.pdf`);
};


export default generateReceipt;